# Generated by Django 5.0.4 on 2024-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacion_producto',
            name='nombre_Clasificacion_Producto',
        ),
        migrations.AddField(
            model_name='clasificacion_producto',
            name='lista_Clasificacion_Producto',
            field=models.CharField(choices=[('opcion1', 'Libros'), ('opcion2', 'Cuadernos'), ('opcion3', 'carpetas')], default='opcion1', max_length=150),
        ),
    ]
