# Generated by Django 5.0.4 on 2024-04-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0004_alter_clasificacion_producto_lista_clasificacion_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_producto',
            old_name='clasificacion_Producto_Producto',
            new_name='clasificacion_Producto',
        ),
    ]
