# Generated by Django 5.0.4 on 2024-04-17 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0005_rename_clasificacion_producto_producto_registro_producto_clasificacion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_producto',
            name='clasificacion_Producto',
        ),
        migrations.AddField(
            model_name='registro_producto',
            name='tipo_Producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria_app.clasificacion_producto'),
        ),
        migrations.AlterField(
            model_name='clasificacion_producto',
            name='lista_Clasificacion_Producto',
            field=models.CharField(choices=[('1', 'Libros'), ('2', 'Cuadernos'), ('3', 'carpetas')], default='1', max_length=150),
        ),
    ]
