# Generated by Django 5.0.4 on 2024-04-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0006_remove_registro_producto_clasificacion_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clasificacion_Producto',
            new_name='clasificacionProducto',
        ),
        migrations.RenameField(
            model_name='registro_producto',
            old_name='tipo_Producto',
            new_name='clasificacion_Producto',
        ),
    ]
