# Generated by Django 5.0.4 on 2024-04-18 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0007_rename_clasificacion_producto_clasificacionproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_producto',
            name='clasificacion_Producto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria_app.clasificacionproducto'),
        ),
    ]
