# Generated by Django 5.0.4 on 2024-04-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0009_registro_producto_imagen_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionproducto',
            name='lista_Clasificacion_Producto',
            field=models.CharField(choices=[('1', 'SELECCIONE'), ('2', 'Lectura'), ('3', 'Material escolar'), ('4', 'carpetas'), ('5', 'Papel'), ('6', 'Escritura'), ('7', 'Manualidades'), ('8', 'Oficina')], default='1', max_length=150),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='cantidad_Producto',
            field=models.IntegerField(default=0, verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='clasificacion_Producto',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='libreria_app.clasificacionproducto', verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='costo_Producto',
            field=models.IntegerField(default=0, verbose_name='Costo del producto'),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='descripcion_Producto',
            field=models.CharField(max_length=100, verbose_name='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='imagen_Producto',
            field=models.ImageField(null=True, upload_to='imagen_producto/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='nombre_Producto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
    ]
