# Generated by Django 5.0.4 on 2024-04-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria_app', '0011_alter_registro_producto_clasificacion_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_producto',
            old_name='id_Producto',
            new_name='id',
        ),
    ]
